# Generated by Django 5.1.7 on 2025-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nahbah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='design',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='design',
            name='design_file',
            field=models.FileField(blank=True, help_text='Upload a PDF or an image', null=True, upload_to='designs/'),
        ),
        migrations.AddField(
            model_name='design',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/previews/'),
        ),
    ]
