# Generated by Django 5.1.7 on 2025-03-26 13:18

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nahbah', '0002_remove_design_image_file_remove_design_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='materials/'),
        ),
    ]
