# Generated by Django 5.1.7 on 2025-03-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nahbah', '0003_material_material_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
