# Generated by Django 5.1.7 on 2025-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nahbah', '0004_alter_design_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
