# Generated by Django 5.1.9 on 2025-10-23 13:26

import nahbah.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nahbah', '0005_design_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_file',
            field=models.FileField(blank=True, help_text='Upload a PDF or an image (max 5MB)', null=True, upload_to='designs/', validators=[nahbah.models.validate_file_size, nahbah.models.validate_file_type]),
        ),
    ]
