# Generated by Django 5.1.9 on 2025-10-27 08:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nahbah', '0006_alter_design_design_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a PDF or an image (max 5MB)', max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='design',
            name='preview_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
