# Generated by Django 5.1.9 on 2025-12-28 16:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nahbah', '0007_alter_design_design_file_alter_design_preview_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a PDF or an image (max 5MB)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
